/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DealInterface extends Interface {
    getFunction(nameOrSignature: "createDeposit" | "deposits" | "getDeposit" | "lockDeposit" | "nextDepositId" | "refundFull" | "splitRelease"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DepositCreated" | "DepositLocked" | "FullRefund" | "SplitRelease"): EventFragment;

    encodeFunctionData(functionFragment: 'createDeposit', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deposits', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockDeposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextDepositId', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundFull', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'splitRelease', values: [BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextDepositId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundFull', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'splitRelease', data: BytesLike): Result;
  }

  
    export namespace DepositCreatedEvent {
      export type InputTuple = [depositId: BigNumberish, buyer: AddressLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [depositId: bigint, buyer: string, seller: string, amount: bigint];
      export interface OutputObject {depositId: bigint, buyer: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositLockedEvent {
      export type InputTuple = [depositId: BigNumberish];
      export type OutputTuple = [depositId: bigint];
      export interface OutputObject {depositId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FullRefundEvent {
      export type InputTuple = [depositId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [depositId: bigint, amount: bigint];
      export interface OutputObject {depositId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SplitReleaseEvent {
      export type InputTuple = [depositId: BigNumberish, repairAmount: BigNumberish, refundAmount: BigNumberish];
      export type OutputTuple = [depositId: bigint, repairAmount: bigint, refundAmount: bigint];
      export interface OutputObject {depositId: bigint, repairAmount: bigint, refundAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Deal extends BaseContract {
    
    connect(runner?: ContractRunner | null): Deal;
    waitForDeployment(): Promise<this>;

    interface: DealInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createDeposit: TypedContractMethod<
      [seller: AddressLike, ],
      [bigint],
      'payable'
    >
    

    
    deposits: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, repairAmount: bigint, refundAmount: bigint, status: bigint }],
      'view'
    >
    

    
    getDeposit: TypedContractMethod<
      [depositId: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, repairAmount: bigint, refundAmount: bigint, status: bigint }],
      'view'
    >
    

    
    lockDeposit: TypedContractMethod<
      [depositId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextDepositId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    refundFull: TypedContractMethod<
      [depositId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    splitRelease: TypedContractMethod<
      [depositId: BigNumberish, repairAmount: BigNumberish, refundAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createDeposit'): TypedContractMethod<
      [seller: AddressLike, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'deposits'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, repairAmount: bigint, refundAmount: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getDeposit'): TypedContractMethod<
      [depositId: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, repairAmount: bigint, refundAmount: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'lockDeposit'): TypedContractMethod<
      [depositId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextDepositId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refundFull'): TypedContractMethod<
      [depositId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'splitRelease'): TypedContractMethod<
      [depositId: BigNumberish, repairAmount: BigNumberish, refundAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DepositCreated'): TypedContractEvent<DepositCreatedEvent.InputTuple, DepositCreatedEvent.OutputTuple, DepositCreatedEvent.OutputObject>;
getEvent(key: 'DepositLocked'): TypedContractEvent<DepositLockedEvent.InputTuple, DepositLockedEvent.OutputTuple, DepositLockedEvent.OutputObject>;
getEvent(key: 'FullRefund'): TypedContractEvent<FullRefundEvent.InputTuple, FullRefundEvent.OutputTuple, FullRefundEvent.OutputObject>;
getEvent(key: 'SplitRelease'): TypedContractEvent<SplitReleaseEvent.InputTuple, SplitReleaseEvent.OutputTuple, SplitReleaseEvent.OutputObject>;

    filters: {
      
      'DepositCreated(uint256,address,address,uint256)': TypedContractEvent<DepositCreatedEvent.InputTuple, DepositCreatedEvent.OutputTuple, DepositCreatedEvent.OutputObject>;
      DepositCreated: TypedContractEvent<DepositCreatedEvent.InputTuple, DepositCreatedEvent.OutputTuple, DepositCreatedEvent.OutputObject>;
    

      'DepositLocked(uint256)': TypedContractEvent<DepositLockedEvent.InputTuple, DepositLockedEvent.OutputTuple, DepositLockedEvent.OutputObject>;
      DepositLocked: TypedContractEvent<DepositLockedEvent.InputTuple, DepositLockedEvent.OutputTuple, DepositLockedEvent.OutputObject>;
    

      'FullRefund(uint256,uint256)': TypedContractEvent<FullRefundEvent.InputTuple, FullRefundEvent.OutputTuple, FullRefundEvent.OutputObject>;
      FullRefund: TypedContractEvent<FullRefundEvent.InputTuple, FullRefundEvent.OutputTuple, FullRefundEvent.OutputObject>;
    

      'SplitRelease(uint256,uint256,uint256)': TypedContractEvent<SplitReleaseEvent.InputTuple, SplitReleaseEvent.OutputTuple, SplitReleaseEvent.OutputObject>;
      SplitRelease: TypedContractEvent<SplitReleaseEvent.InputTuple, SplitReleaseEvent.OutputTuple, SplitReleaseEvent.OutputObject>;
    
    };
  }