/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Deal } from './Deal.js';
export * as factories from './factories/index.js';
export { Deal__factory } from './factories/Deal__factory.js';