import type {
  AnalyticsStats,
  CategorySlice,
  Deal,
  EarningsPoint,
  TimelineEvent,
  User,
} from "./types";

export const CURRENT_USER: User = {
  id: "user_constructora",
  whatsapp_number: "+51 987 654 321",
  wallet_address: "0x4f2c…a91b",
  display_name: "Constructora Andes",
  profile_photo_url: "",
  rating: 4.9,
  deal_count: 12,
};

const cliente: User = {
  id: "user_cliente",
  whatsapp_number: "+51 912 000 111",
  wallet_address: "0x8ab1…33e0",
  display_name: "María Quispe",
  profile_photo_url: "",
  rating: 4.8,
  deal_count: 4,
};

const huesped: User = {
  id: "user_huesped",
  whatsapp_number: "+51 999 111 222",
  wallet_address: "0x22c9…bb10",
  display_name: "Diego Ramos",
  profile_photo_url: "",
  rating: 4.6,
  deal_count: 3,
};

const anfitrion: User = {
  id: "user_host",
  whatsapp_number: "+51 955 333 444",
  wallet_address: "0xAb12…9f01",
  display_name: "Lucía Host — Miraflores",
  profile_photo_url: "",
  rating: 4.9,
  deal_count: 28,
};

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal_xyz789",
    seller: CURRENT_USER,
    buyer: cliente,
    service: "Remodelación cocina completa",
    description:
      "Demolición, instalación de gabinetes y acabados. Pago por hitos. Monto alto con guardrails extra.",
    amount_pen: 12000,
    amount_usdt: 3250,
    status: "escrowed",
    deal_type: "service",
    is_milestone_based: true,
    high_value: true,
    created_at: "2026-08-20T10:00:00Z",
    completed_at: null,
    smart_contract_address: "0x9f8e7d6c5b4a3210",
    checkin_at: null,
    checkout_at: null,
    repair_amount_pen: null,
    refund_amount_pen: null,
    claimed_damage_pen: null,
    milestones: [
      {
        id: "ms_1",
        deal_id: "deal_xyz789",
        order_index: 1,
        description: "Demolición",
        amount_pen: 2400,
        amount_usdt: 650,
        status: "completed",
        unlocked_at: "2026-08-20T10:05:00Z",
        completed_at: "2026-08-23T15:27:00Z",
      },
      {
        id: "ms_2",
        deal_id: "deal_xyz789",
        order_index: 2,
        description: "Instalación",
        amount_pen: 6000,
        amount_usdt: 1625,
        status: "arbitrating",
        unlocked_at: "2026-08-23T15:28:00Z",
        completed_at: null,
      },
      {
        id: "ms_3",
        deal_id: "deal_xyz789",
        order_index: 3,
        description: "Acabados",
        amount_pen: 3600,
        amount_usdt: 975,
        status: "locked",
        unlocked_at: null,
        completed_at: null,
      },
    ],
    photos: [
      {
        id: "ph_1",
        deal_id: "deal_xyz789",
        uploaded_by: CURRENT_USER.id,
        ipfs_hash: "QmKitchenDemo01",
        caption: "Hito 1 — demolición completa",
        metadata: {
          timestamp: "2026-08-23T15:20:00Z",
          gps: { lat: -12.0462, lon: -77.0371 },
          device: "iPhone 14 Pro",
        },
      },
      {
        id: "ph_2",
        deal_id: "deal_xyz789",
        uploaded_by: CURRENT_USER.id,
        ipfs_hash: "QmKitchenInst02",
        caption: "Hito 2 — gabinetes instalados",
        metadata: {
          timestamp: "2026-08-24T10:12:00Z",
          gps: { lat: -12.0462, lon: -77.0371 },
          device: "iPhone 14 Pro",
        },
      },
    ],
    payments: [
      {
        id: "pay_1",
        deal_id: "deal_xyz789",
        kapso_payment_id: "kapso_2400",
        amount_pen: 2400,
        currency: "PEN",
        status: "confirmed",
        confirmed_at: "2026-08-20T11:02:00Z",
      },
      {
        id: "pay_2",
        deal_id: "deal_xyz789",
        kapso_payment_id: "kapso_6000",
        amount_pen: 6000,
        currency: "PEN",
        status: "confirmed",
        confirmed_at: "2026-08-23T16:40:00Z",
      },
    ],
    arbitration: [
      {
        id: "arb_ms1_g",
        deal_id: "deal_xyz789",
        agent_name: "gemini",
        status: "complete",
        progress: 100,
        decision: "CUMPLIDO",
        confidence: 97,
        reasoning: "Alcance de demolición cubierto. Escombros retirados.",
      },
      {
        id: "arb_ms1_c",
        deal_id: "deal_xyz789",
        agent_name: "claude",
        status: "complete",
        progress: 100,
        decision: "CUMPLIDO",
        confidence: 96,
        reasoning: "Fotos coinciden con el hito 1 del acuerdo.",
      },
    ],
    payouts: [
      {
        id: "po_1",
        deal_id: "deal_xyz789",
        milestone_id: "ms_1",
        role: "payment",
        tx_hash: "0x9f8e7d6c5b4a3210ffee",
        amount_usdt: 650,
        recipient: CURRENT_USER.display_name,
        status: "confirmed",
        confirmed_at: "2026-08-23T15:27:00Z",
      },
    ],
    ratings: [],
  },
  {
    id: "deal_deposit_456",
    seller: anfitrion,
    buyer: huesped,
    service: "Depósito de garantía — Depto Miraflores",
    description:
      "Depósito reembolsable bloqueado on-chain antes del check-in. Posible split si hay daños.",
    amount_pen: 800,
    amount_usdt: 216,
    status: "disputed",
    deal_type: "deposit",
    is_milestone_based: false,
    high_value: false,
    created_at: "2026-08-28T09:00:00Z",
    completed_at: null,
    smart_contract_address: "0xAb12Cd34Ef56",
    checkin_at: "2026-08-28T15:00:00Z",
    checkout_at: "2026-08-31T11:00:00Z",
    repair_amount_pen: 220,
    refund_amount_pen: 580,
    claimed_damage_pen: 300,
    milestones: [],
    photos: [
      {
        id: "ph_d1",
        deal_id: "deal_deposit_456",
        uploaded_by: anfitrion.id,
        ipfs_hash: "QmBefore01",
        caption: "Antes — living",
        metadata: { timestamp: "2026-08-28T14:50:00Z", device: "Pixel 8" },
      },
      {
        id: "ph_d2",
        deal_id: "deal_deposit_456",
        uploaded_by: anfitrion.id,
        ipfs_hash: "QmAfter01",
        caption: "Después — living (daño reportado)",
        metadata: { timestamp: "2026-08-31T14:20:00Z", device: "Pixel 8" },
      },
    ],
    payments: [
      {
        id: "pay_d1",
        deal_id: "deal_deposit_456",
        kapso_payment_id: "kapso_dep_800",
        amount_pen: 800,
        currency: "PEN",
        status: "confirmed",
        confirmed_at: "2026-08-28T09:05:00Z",
      },
    ],
    arbitration: [
      {
        id: "arb_d_g",
        deal_id: "deal_deposit_456",
        agent_name: "gemini",
        status: "processing",
        progress: 62,
        decision: null,
        confidence: null,
        reasoning: "Comparando fotos antes/después…",
      },
      {
        id: "arb_d_c",
        deal_id: "deal_deposit_456",
        agent_name: "claude",
        status: "processing",
        progress: 41,
        decision: null,
        confidence: null,
        reasoning: "Evaluando reclamo de S/300…",
      },
    ],
    payouts: [],
    ratings: [],
  },
  {
    id: "deal_plomeria_88",
    seller: CURRENT_USER,
    buyer: cliente,
    service: "Reparación de fuga — baño",
    description: "Servicio puntual. Un solo pago Kapso.",
    amount_pen: 180,
    amount_usdt: 49,
    status: "completed",
    deal_type: "service",
    is_milestone_based: false,
    high_value: false,
    created_at: "2026-08-12T18:00:00Z",
    completed_at: "2026-08-12T19:10:00Z",
    smart_contract_address: "0x11aa22bb",
    checkin_at: null,
    checkout_at: null,
    repair_amount_pen: null,
    refund_amount_pen: null,
    claimed_damage_pen: null,
    milestones: [],
    photos: [
      {
        id: "ph_p1",
        deal_id: "deal_plomeria_88",
        uploaded_by: CURRENT_USER.id,
        ipfs_hash: "QmPipe01",
        caption: "Fuga reparada",
        metadata: { timestamp: "2026-08-12T18:40:00Z" },
      },
    ],
    payments: [
      {
        id: "pay_p1",
        deal_id: "deal_plomeria_88",
        kapso_payment_id: "kapso_180",
        amount_pen: 180,
        currency: "PEN",
        status: "confirmed",
        confirmed_at: "2026-08-12T18:05:00Z",
      },
    ],
    arbitration: [
      {
        id: "arb_p_g",
        deal_id: "deal_plomeria_88",
        agent_name: "gemini",
        status: "complete",
        progress: 100,
        decision: "CUMPLIDO",
        confidence: 99,
        reasoning: "Evidencia clara del arreglo.",
      },
      {
        id: "arb_p_c",
        deal_id: "deal_plomeria_88",
        agent_name: "claude",
        status: "complete",
        progress: 100,
        decision: "CUMPLIDO",
        confidence: 98,
        reasoning: "Consenso 2/2.",
      },
    ],
    payouts: [
      {
        id: "po_p1",
        deal_id: "deal_plomeria_88",
        milestone_id: null,
        role: "payment",
        tx_hash: "0xa1b2c3d4e5",
        amount_usdt: 49,
        recipient: CURRENT_USER.display_name,
        status: "confirmed",
        confirmed_at: "2026-08-12T19:10:00Z",
      },
    ],
    ratings: [
      {
        from: cliente.display_name,
        to: CURRENT_USER.display_name,
        score: 5,
        comment: "Llegó rápido y el pago salió solo.",
      },
    ],
  },
];

export const MOCK_STATS: AnalyticsStats = {
  total_earned: 3250 + 49,
  deals_completed: 2,
  rating: 4.9,
  success_rate: 100,
  avg_time_to_payout: 25,
};

export const MOCK_EARNINGS: EarningsPoint[] = [
  { month: "Mar", earnings: 420 },
  { month: "Abr", earnings: 680 },
  { month: "May", earnings: 510 },
  { month: "Jun", earnings: 890 },
  { month: "Jul", earnings: 740 },
  { month: "Ago", earnings: 699 },
];

export const MOCK_CATEGORIES: CategorySlice[] = [
  { category: "Remodelación", amount: 650 },
  { category: "Plomería", amount: 49 },
  { category: "Depósitos", amount: 0 },
];

export const MOCK_TIMELINE: TimelineEvent[] = [
  { date: "2026-08-23T15:27:00Z", event: "Payout hito 1 — Demolición", amount: 650, status: "confirmed" },
  { date: "2026-08-12T19:10:00Z", event: "Payout plomería", amount: 49, status: "confirmed" },
  { date: "2026-08-28T09:05:00Z", event: "Depósito bloqueado on-chain", amount: 216, status: "locked" },
];
